status = [
  "Linux Container python:3.7 py37",
  "Linux Container python:3.7 py37-benchmark",
  "Linux Container python:3.7 py37-speedups",
  "Linux Container python:3.8 py38",
  "Linux Container python:3.8 py38-benchmark",
  "Linux Container python:3.8 py38-speedups",
  "Linux Container python:3.9 py39",
  "Linux Container python:3.9 py39-benchmark",
  "Linux Container python:3.9 py39-speedups",
  "Linux Container python:3.10 py310",
  "Linux Container python:3.10 py310-benchmark",
  "Linux Container python:3.10 py310-speedups",
  "Linux Container pypy:3 pypy3",
  "Linux Container python:3.9 check-manifest",
  "Linux Container python:3.9 checkreadme",
  "Linux Container python:3.9 docs",
  "Linux Container python:3.9 flake8",
  "Linux Container python:3.9 pylint",
  "Windows py37",
  "Windows py37-speedups",
  "Windows py38",
  "Windows py38-speedups",
  "Windows py39",
  "Windows py39-speedups",
  "Windows py310",
  "Windows py310-speedups",
]
