name: tox

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  linux-container-tests:
    name: "Linux Container ${{ matrix.image }} ${{ matrix.tox_envs }}"
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        include:
          - image: "python:3.7"
            tox_envs: "py37"
          - image: "python:3.8"
            tox_envs: "py38"
          - image: "python:3.9"
            tox_envs: "py39"
          - image: "python:3.10"
            tox_envs: "py310"
          - image: "python:3.7"
            tox_envs: "py37-speedups"
          - image: "python:3.8"
            tox_envs: "py38-speedups"
          - image: "python:3.9"
            tox_envs: "py39-speedups"
          - image: "python:3.10"
            tox_envs: "py310-speedups"
          - image: "python:3.7"
            tox_envs: "py37-benchmark"
          - image: "python:3.8"
            tox_envs: "py38-benchmark"
          - image: "python:3.9"
            tox_envs: "py39-benchmark"
          - image: "python:3.10"
            tox_envs: "py310-benchmark"
          - image: "python:3.9"
            tox_envs: "docs"
          - image: "python:3.9"
            tox_envs: "flake8"
          - image: "python:3.9"
            tox_envs: "pylint"
          - image: "python:3.9"
            tox_envs: "check-manifest"
          - image: "python:3.9"
            tox_envs: "checkreadme"
          - image: "pypy:3"
            tox_envs: "pypy3"

    container:
      image: "${{ matrix.image }}"
    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis
    env:
      REDIS_HOST: redis
    steps:
      - uses: "actions/checkout@v2"
      - name: "Install dependencies"
        run: |
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --upgrade tox
      - name: "Run tox targets for ${{ matrix.tox_envs }}"
        run: "python -m tox -e ${{ matrix.tox_envs }}"
  windows:
    name: "Windows ${{ matrix.tox_envs }}"
    runs-on: windows-latest
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        include:
          - python-version: "3.7"
            tox_envs: "py37"
          - python-version: "3.8"
            tox_envs: "py38"
          - python-version: "3.9"
            tox_envs: "py39"
          - python-version: "3.10"
            tox_envs: "py310"
          - python-version: "3.7"
            tox_envs: "py37-speedups"
          - python-version: "3.8"
            tox_envs: "py38-speedups"
          - python-version: "3.9"
            tox_envs: "py39-speedups"
          - python-version: "3.10"
            tox_envs: "py310-speedups"

    env:
      ENABLE_LOGBOOK_NTEVENTLOG_TESTS: TRUE
    steps:
      - uses: "actions/checkout@v2"
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: "Install dependencies"
        run: |
          python -VV
          python -m site
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install --upgrade tox
      - name: "Run tox targets for ${{ matrix.tox_envs }}"
        run: "python -m tox -e ${{ matrix.tox_envs }}"
